nohup torchrun --nproc_per_node=4 --master_port=20001 fastchat/train/train_mem.py \
    --model_name_or_path /home/lan/CodeSpace/LLM_downloads/decapoda-research/llama-13b-hf  \
    --data_path playground/data/dummy2.json \
    --bf16 True \
    --output_dir output/vicuna_13b_dummy1/ \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no"\
    --save_strategy "steps"\
    --save_steps 1 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine"\
    --logging_steps 1 \
    --model_max_length 256 \
    --gradient_checkpointing True \
    --lazy_preprocess True\
    --deepspeed "./configs/default_offload_opt_param_vicuna13B.json"&>"./logs/13b1.log"&